const gameActionTypes = {
  FETCH_GAMES_START: 'FETCH_GAMES_START',
  FETCH_GAMES_SUCCESS: 'FETCH_GAMES_SUCCESS',
  FETCH_GAMES_FAILURE: 'FETCH_GAMES_FAILURE',
  SET_SEARCH_VALUE: 'SET_SEARCH_VALUE',
  SET_FILTER_VALUE: 'SET_FILTER_VALUE',
  TOGGLE_FILTER: 'TOGGLE_FILTER'
}

export default gameActionTypes;